name: CI
on: [push]
jobs:
  build:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
